# h2 DB config
spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
  h2:
    console.enabled: true

  spring:
    jpa:
      hibernate:
        use-new-id-generator-mappings: false
